const BANGLADESH_DISTRICTS = [
  { value: "Bagerhat", bn: "বাগেরহাট", division: "Khulna" },
  { value: "Bandarban", bn: "বান্দরবান", division: "Chattogram" },
  { value: "Barguna", bn: "বরগুনা", division: "Barishal" },
  { value: "Barishal", bn: "বরিশাল", division: "Barishal" },
  { value: "Bhola", bn: "ভোলা", division: "Barishal" },
  { value: "Bogura", bn: "বগুড়া", division: "Rajshahi" },
  { value: "Brahmanbaria", bn: "ব্রাহ্মণবাড়িয়া", division: "Chattogram" },
  { value: "Chandpur", bn: "চাঁদপুর", division: "Chattogram" },
  { value: "Chapainawabganj", bn: "চাঁপাইনবাবগঞ্জ", division: "Rajshahi" },
  { value: "Chattogram", bn: "চট্টগ্রাম", division: "Chattogram" },
  { value: "Chuadanga", bn: "চুয়াডাঙ্গা", division: "Khulna" },
  { value: "Cox's Bazar", bn: "কক্সবাজার", division: "Chattogram" },
  { value: "Cumilla", bn: "কুমিল্লা", division: "Chattogram" },
  { value: "Dhaka", bn: "ঢাকা", division: "Dhaka" },
  { value: "Dinajpur", bn: "দিনাজপুর", division: "Rangpur" },
  { value: "Faridpur", bn: "ফরিদপুর", division: "Dhaka" },
  { value: "Feni", bn: "ফেনী", division: "Chattogram" },
  { value: "Gaibandha", bn: "গাইবান্ধা", division: "Rangpur" },
  { value: "Gazipur", bn: "গাজীপুর", division: "Dhaka" },
  { value: "Gopalganj", bn: "গোপালগঞ্জ", division: "Dhaka" },
  { value: "Habiganj", bn: "হবিগঞ্জ", division: "Sylhet" },
  { value: "Jamalpur", bn: "জামালপুর", division: "Mymensingh" },
  { value: "Jashore", bn: "যশোর", division: "Khulna" },
  { value: "Jhalokati", bn: "ঝালকাঠি", division: "Barishal" },
  { value: "Jhenaidah", bn: "ঝিনাইদহ", division: "Khulna" },
  { value: "Joypurhat", bn: "জয়পুরহাট", division: "Rajshahi" },
  { value: "Khagrachhari", bn: "খাগড়াছড়ি", division: "Chattogram" },
  { value: "Khulna", bn: "খুলনা", division: "Khulna" },
  { value: "Kishoreganj", bn: "কিশোরগঞ্জ", division: "Dhaka" },
  { value: "Kurigram", bn: "কুড়িগ্রাম", division: "Rangpur" },
  { value: "Kushtia", bn: "কুষ্টিয়া", division: "Khulna" },
  { value: "Lakshmipur", bn: "লক্ষ্মীপুর", division: "Chattogram" },
  { value: "Lalmonirhat", bn: "লালমনিরহাট", division: "Rangpur" },
  { value: "Madaripur", bn: "মাদারীপুর", division: "Dhaka" },
  { value: "Magura", bn: "মাগুরা", division: "Khulna" },
  { value: "Manikganj", bn: "মানিকগঞ্জ", division: "Dhaka" },
  { value: "Meherpur", bn: "মেহেরপুর", division: "Khulna" },
  { value: "Moulvibazar", bn: "মৌলভীবাজার", division: "Sylhet" },
  { value: "Munshiganj", bn: "মুন্সিগঞ্জ", division: "Dhaka" },
  { value: "Mymensingh", bn: "ময়মনসিংহ", division: "Mymensingh" },
  { value: "Naogaon", bn: "নওগাঁ", division: "Rajshahi" },
  { value: "Narail", bn: "নড়াইল", division: "Khulna" },
  { value: "Narayanganj", bn: "নারায়ণগঞ্জ", division: "Dhaka" },
  { value: "Narsingdi", bn: "নরসিংদী", division: "Dhaka" },
  { value: "Natore", bn: "নাটোর", division: "Rajshahi" },
  { value: "Netrokona", bn: "নেত্রকোনা", division: "Mymensingh" },
  { value: "Nilphamari", bn: "নীলফামারী", division: "Rangpur" },
  { value: "Noakhali", bn: "নোয়াখালী", division: "Chattogram" },
  { value: "Pabna", bn: "পাবনা", division: "Rajshahi" },
  { value: "Panchagarh", bn: "পঞ্চগড়", division: "Rangpur" },
  { value: "Patuakhali", bn: "পটুয়াখালী", division: "Barishal" },
  { value: "Pirojpur", bn: "পিরোজপুর", division: "Barishal" },
  { value: "Rajbari", bn: "রাজবাড়ী", division: "Dhaka" },
  { value: "Rajshahi", bn: "রাজশাহী", division: "Rajshahi" },
  { value: "Rangamati", bn: "রাঙ্গামাটি", division: "Chattogram" },
  { value: "Rangpur", bn: "রংপুর", division: "Rangpur" },
  { value: "Satkhira", bn: "সাতক্ষীরা", division: "Khulna" },
  { value: "Shariatpur", bn: "শরীয়তপুর", division: "Dhaka" },
  { value: "Sherpur", bn: "শেরপুর", division: "Mymensingh" },
  { value: "Sirajganj", bn: "সিরাজগঞ্জ", division: "Rajshahi" },
  { value: "Sunamganj", bn: "সুনামগঞ্জ", division: "Sylhet" },
  { value: "Sylhet", bn: "সিলেট", division: "Sylhet" },
  { value: "Tangail", bn: "টাঙ্গাইল", division: "Dhaka" },
  { value: "Thakurgaon", bn: "ঠাকুরগাঁও", division: "Rangpur" },
];

const DISTRICT_VALUES = BANGLADESH_DISTRICTS.map((district) => district.value);

module.exports = { BANGLADESH_DISTRICTS, DISTRICT_VALUES };
