const USER_ROLES = ["USER", "MODERATOR", "ADMIN", "SUPER_ADMIN"];
const CAPABILITIES = ["TENANT", "PROPERTY_OWNER", "EMPLOYER", "JOB_SEEKER", "MARKET_SELLER"];
const ACCOUNT_STATUSES = ["PENDING_VERIFICATION", "ACTIVE", "SUSPENDED"];
const OTP_PURPOSES = ["LOGIN", "SIGNUP", "PASSWORD_RESET", "PHONE_CHANGE", "ADMIN_LOGIN"];

const PROPERTY_KINDS = ["RESIDENTIAL", "COMMERCIAL"];
const RESIDENTIAL_CATEGORIES = [
  "APARTMENT",
  "FULL_HOUSE",
  "ROOM",
  "SUBLET",
  "BACHELOR_ACCOMMODATION",
  "STUDIO",
  "FURNISHED_APARTMENT",
];
const COMMERCIAL_CATEGORIES = ["SHOP", "OFFICE", "SHOWROOM", "WAREHOUSE", "COMMERCIAL_SPACE"];
const PROPERTY_STATUSES = [
  "DRAFT",
  "PENDING_REVIEW",
  "CHANGES_REQUIRED",
  "ACTIVE",
  "RESERVED",
  "RENTED",
  "EXPIRED",
  "REJECTED",
  "SUSPENDED",
];
const PROPERTY_AVAILABILITY_STATUSES = ["AVAILABLE", "NOT_SURE", "RESERVED", "RENTED"];

const MARKET_CATEGORIES = [
  "MOBILE_TABLET",
  "ELECTRONICS_APPLIANCES",
  "HOME_FURNITURE",
  "VEHICLES_PARTS",
  "FASHION_PERSONAL",
  "SPORTS_HOBBIES",
  "BUSINESS_EQUIPMENT",
  "OTHER",
];
const MARKET_CONDITIONS = ["NEW", "LIKE_NEW", "USED"];
const MARKET_LISTING_STATUSES = [
  "DRAFT",
  "PENDING_REVIEW",
  "CHANGES_REQUIRED",
  "ACTIVE",
  "SOLD",
  "EXPIRED",
  "REJECTED",
  "SUSPENDED",
];

const TENANT_TYPES = [
  "FAMILY",
  "BACHELOR_MALE",
  "BACHELOR_FEMALE",
  "STUDENT_MALE",
  "STUDENT_FEMALE",
  "WORKING_PROFESSIONAL",
  "CORPORATE",
  "SUBLET",
  "SHARED_ROOM",
  "HOSTEL_MESS",
  "ANY",
];

const REQUEST_STATUSES = [
  "DRAFT",
  "PENDING_REVIEW",
  "CHANGES_REQUIRED",
  "ACTIVE",
  "MATCHED",
  "FULFILLED",
  "EXPIRED",
  "REJECTED",
  "SUSPENDED",
];

const JOB_CATEGORIES = [
  "CARETAKER",
  "SECURITY_GUARD",
  "CLEANER",
  "DRIVER",
  "ELECTRICIAN",
  "PLUMBER",
  "PAINTER",
  "AC_TECHNICIAN",
  "CARPENTER",
  "COOK",
  "HOUSEKEEPER",
  "MOVING_HELPER",
  "PROPERTY_MANAGER",
  "SALES_AGENT",
  "HOME_ASSISTANT",
  "PEST_CONTROL",
  "APPLIANCE_TECHNICIAN",
];
const JOB_TYPES = ["FULL_TIME", "PART_TIME", "CONTRACT", "DAILY"];
const JOB_STATUSES = [
  "DRAFT",
  "PENDING_REVIEW",
  "CHANGES_REQUIRED",
  "ACTIVE",
  "FILLED",
  "CLOSED",
  "EXPIRED",
  "REJECTED",
  "SUSPENDED",
];
const APPLICATION_STATUSES = ["APPLIED", "VIEWED", "SHORTLISTED", "HIRED", "REJECTED", "WITHDRAWN"];
const WORKER_PROFILE_STATUSES = ["DRAFT", "PENDING_REVIEW", "CHANGES_REQUIRED", "ACTIVE", "PAUSED", "REJECTED", "SUSPENDED"];
const HIRE_INVITATION_STATUSES = ["SENT", "VIEWED", "ACCEPTED", "DECLINED", "WITHDRAWN"];
const REPORT_STATUSES = ["OPEN", "IN_REVIEW", "RESOLVED", "DISMISSED"];
const REPORT_REASONS = ["ALREADY_RENTED", "FAKE", "WRONG_INFO", "DUPLICATE", "SCAM", "PROHIBITED", "OTHER"];

const PROPERTY_AMENITIES = [
  "LIFT",
  "PARKING",
  "GENERATOR",
  "CCTV",
  "SECURITY",
  "GAS",
  "WATER",
  "INTERNET",
  "FURNISHED",
  "AC",
  "GEYSER",
  "WASHROOM",
  "ELECTRICITY",
];

module.exports = {
  USER_ROLES,
  CAPABILITIES,
  ACCOUNT_STATUSES,
  OTP_PURPOSES,
  PROPERTY_KINDS,
  RESIDENTIAL_CATEGORIES,
  COMMERCIAL_CATEGORIES,
  PROPERTY_STATUSES,
  PROPERTY_AVAILABILITY_STATUSES,
  MARKET_CATEGORIES,
  MARKET_CONDITIONS,
  MARKET_LISTING_STATUSES,
  TENANT_TYPES,
  REQUEST_STATUSES,
  JOB_CATEGORIES,
  JOB_TYPES,
  JOB_STATUSES,
  APPLICATION_STATUSES,
  WORKER_PROFILE_STATUSES,
  HIRE_INVITATION_STATUSES,
  REPORT_STATUSES,
  REPORT_REASONS,
  PROPERTY_AMENITIES,
};
